module gpu_manager
  use cudafor
  use nvtx
  use gpu_utils
  use gpu_runner
  use ramses_commons, only: ramses_t
contains
!###########################################################
!###########################################################
!###########################################################
!###########################################################
recursive subroutine r_set_grid_device(pst)
  use mdl_module
  use ramses_commons, only: pst_t
  use refine_device, only: insert_hash_kernel, update_nbor_array
  use mdl_parameters
  implicit none
  type(pst_t)::pst

  integer::rID
  integer::head_idx, num_octs, num_subgrids, num_threads, num_blocks, ind

  if(pst%nLower>0)then
     rID = mdl_send_request(pst%s%mdl,MDL_SET_GRID_DEVICE,pst%iUpper+1)
     call r_set_grid_device(pst%pLower)
     call mdl_get_reply(pst%s%mdl,rID,0)
  else

     ! Copy grid from host to device
     call nvtxStartRange("Copy entire mesh from host to device", color=5)!red
     grid = pst%s%m%grid
     ! flag1 is only allocated/used for adaptive mesh refinement
     if(pst%s%r%nlevelmax > pst%s%r%levelmin) flag1 = pst%s%m%flag1
#ifdef HYDRO
     uold = pst%s%m%uold
#ifdef MHD
     bold = pst%s%m%bold
#endif
#endif
     call GPU_Error_Check(__FILE__, __LINE__)
     call nvtxEndRange()

     ! Particle H→D
     if (pst%s%r%part .and. allocated(pst%s%p%xp) .and. allocated(xp)) then
        call nvtxStartRange("Copy part from host to device", color=5)!red
        xp     = pst%s%p%xp
        vp     = pst%s%p%vp
        mp     = pst%s%p%mp
        levelp = pst%s%p%levelp
        sortp  = pst%s%p%sortp
        if (allocated(idp)) idp = pst%s%p%idp
        call GPU_Error_Check(__FILE__, __LINE__)
        call nvtxEndRange()
     endif

     ! Star particle H→D
     if (pst%s%r%star .and. allocated(pst%s%star%xp) .and. allocated(star_xp)) then
        call nvtxStartRange("Copy star from host to device", color=5)!red
        star_xp     = pst%s%star%xp
        star_vp     = pst%s%star%vp
        star_mp     = pst%s%star%mp
        star_tp     = pst%s%star%tp
        star_zp     = pst%s%star%zp
        star_levelp = pst%s%star%levelp
        star_sortp  = pst%s%star%sortp
        if (allocated(star_idp)) star_idp = pst%s%star%idp
        call GPU_Error_Check(__FILE__, __LINE__)
        call nvtxEndRange()
     endif

     ! Sink particle H→D
     if (pst%s%r%sink .and. allocated(pst%s%sink%xp) .and. allocated(sink_xp)) then
        call nvtxStartRange("Copy sink from host to device", color=5)!red
        sink_xp     = pst%s%sink%xp
        sink_vp     = pst%s%sink%vp
        sink_fp     = pst%s%sink%fp
        sink_jp     = pst%s%sink%jp
        sink_mp     = pst%s%sink%mp
        sink_tp     = pst%s%sink%tp
        sink_levelp = pst%s%sink%levelp
        sink_sortp  = pst%s%sink%sortp
        if (allocated(sink_idp)) sink_idp = pst%s%sink%idp
        if (allocated(sink_pid) .and. allocated(pst%s%sink%pid)) sink_pid = pst%s%sink%pid
        call GPU_Error_Check(__FILE__, __LINE__)
        call nvtxEndRange()
     endif

     ! Insert entire grid in the device hash table
     head_idx = 1
     num_octs = pst%s%m%ifree - 1
     num_threads = 128
     num_blocks = (num_octs + num_threads - 1) / num_threads

     call nvtxStartRange("Insert grid in hash table", color=5)!red
     call insert_hash_kernel<<<num_blocks, num_threads>>>(grid, hash_key, hash_val, pst%s%m%hash_size, &
          & ckey_max, key_off, head_idx, num_octs)
     call GPU_Error_Check(__FILE__, __LINE__)
     call nvtxEndRange()

     ! Compute nbor grids array for coarse level only
     head_idx = 1
     num_subgrids = pst%s%m%noct(pst%s%r%levelmin) / nsubgridtondim
     num_threads = 128
     num_blocks = (num_subgrids + num_threads - 1) / num_threads
     call nvtxStartRange("Compute nbor array", color=5)!red
     do ind = 1, subgridsize
        call update_nbor_array<<<num_blocks, num_threads>>>(nbor, grid, hash_key, hash_val, pst%s%m%hash_size, &
             & ckey_max, key_off, box_ckey_min, box_ckey_max, periodic, head_idx, num_subgrids, ind)
     end do
     call GPU_Error_Check(__FILE__, __LINE__)
     call nvtxEndRange()

     pst%s%m%data_on_device=.true.

  endif

end subroutine r_set_grid_device
!###########################################################
!###########################################################
!###########################################################
!###########################################################
recursive subroutine r_transfer_grid_host(pst)
  use mdl_module
  use ramses_commons, only: pst_t
  use mdl_parameters
  implicit none
  type(pst_t)::pst

  integer::rID

  if(pst%nLower>0)then
     rID = mdl_send_request(pst%s%mdl,MDL_TRANSFER_GRID_HOST,pst%iUpper+1)
     call r_transfer_grid_host(pst%pLower)
     call mdl_get_reply(pst%s%mdl,rID,0)
  else

     ! Copy grid from device to host
     call nvtxStartRange("Copy entire mesh from device to host", color=5)!red
     if(pst%s%r%nlevelmax > pst%s%r%levelmin) pst%s%m%grid = grid
#ifdef HYDRO
     pst%s%m%uold = uold
#ifdef MHD
     pst%s%m%bold = bold
#endif
#endif
#ifdef GRAV
     pst%s%m%f = f
     pst%s%m%phi = phi
#endif
     call GPU_Error_Check(__FILE__, __LINE__)
     call nvtxEndRange()

     if(pst%s%r%pic)then
        call gpu_to_host_part(pst)
     endif

  endif

end subroutine r_transfer_grid_host
!###########################################################
!###########################################################
!###########################################################
!###########################################################
subroutine gpu_to_host_part(pst)
  use ramses_commons, only: pst_t
  implicit none
  type(pst_t)::pst

  if (allocated(xp)) then
     call nvtxStartRange("Copy part from device to host", color=5)!red
     pst%s%p%xp     = xp
     pst%s%p%vp     = vp
     pst%s%p%mp     = mp
     pst%s%p%levelp = levelp
     pst%s%p%sortp  = sortp
     if (allocated(idp)) pst%s%p%idp = idp
     call GPU_Error_Check(__FILE__, __LINE__)
     call nvtxEndRange()
  endif

  if (allocated(star_xp)) then
     call nvtxStartRange("Copy star from device to host", color=5)!red
     pst%s%star%xp     = star_xp
     pst%s%star%vp     = star_vp
     pst%s%star%mp     = star_mp
     pst%s%star%tp     = star_tp
     pst%s%star%zp     = star_zp
     pst%s%star%levelp = star_levelp
     pst%s%star%sortp  = star_sortp
     if (allocated(star_idp)) pst%s%star%idp = star_idp
     call GPU_Error_Check(__FILE__, __LINE__)
     call nvtxEndRange()
  endif

  if (allocated(sink_xp)) then
     call nvtxStartRange("Copy sink from device to host", color=5)!red
     pst%s%sink%xp     = sink_xp
     pst%s%sink%vp     = sink_vp
     pst%s%sink%fp     = sink_fp
     pst%s%sink%jp     = sink_jp
     pst%s%sink%mp     = sink_mp
     pst%s%sink%tp     = sink_tp
     pst%s%sink%levelp = sink_levelp
     pst%s%sink%sortp  = sink_sortp
     if (allocated(sink_idp)) pst%s%sink%idp = sink_idp
     if (allocated(sink_pid) .and. allocated(pst%s%sink%pid)) pst%s%sink%pid = sink_pid
     call GPU_Error_Check(__FILE__, __LINE__)
     call nvtxEndRange()
  endif

end subroutine gpu_to_host_part
!###########################################################
!###########################################################
!###########################################################
subroutine gpu_turb_init_fields(pst)
  use ramses_commons, only: pst_t
  implicit none
  type(pst_t)::pst

  if (.not. allocated(afield_next_d)) return

  call nvtxStartRange("Copy initial turb fields host to device", color=5)!red
  afield_last_d = pst%s%turb%afield_last
  afield_next_d = pst%s%turb%afield_next
  afield_now_d  = pst%s%turb%afield_now
  call GPU_Error_Check(__FILE__, __LINE__)
  call nvtxEndRange()

end subroutine gpu_turb_init_fields
!###########################################################
!###########################################################
!###########################################################
subroutine gpu_turb_next_field(pst)
  use ramses_commons, only: pst_t
  implicit none
  type(pst_t)::pst

  if (.not. allocated(afield_next_d)) return

  call nvtxStartRange("Rotate + upload turb afield_next", color=5)!red
  afield_last_d = afield_next_d
  afield_next_d = pst%s%turb%afield_next
  call GPU_Error_Check(__FILE__, __LINE__)
  call nvtxEndRange()

end subroutine gpu_turb_next_field
!###########################################################
!###########################################################
!###########################################################
subroutine gpu_update_turb(pst)
  use ramses_commons, only: pst_t
  use turb_commons, only: turb_next_field
  implicit none
  type(pst_t)::pst
  real(kind=8) :: last_tfrac, next_tfrac

  ! Advance the host field(s) and mirror each new one to the device.
  do
     if (pst%s%g%t >= pst%s%turb%turb_next_time) then
        call turb_next_field(pst%s%r, pst%s%turb)
        call gpu_turb_next_field(pst)
     else
        exit
     end if
  end do

  ! Device time-interpolation.
  call gpu_turb_interp(pst%s)

  ! Keep the host afield_now in sync for host-side diagnostics.
  last_tfrac = (pst%s%g%t - pst%s%turb%turb_last_time)/pst%s%turb%turb_dt
  next_tfrac = 1d0 - last_tfrac
  pst%s%turb%afield_now = next_tfrac*pst%s%turb%afield_last + last_tfrac*pst%s%turb%afield_next

end subroutine gpu_update_turb
!###########################################################
!###########################################################
!###########################################################
!###########################################################
subroutine gpu_allocate_amr(sim)
  use amr_parameters, ONLY: ndim, twotondim
#ifdef HYDRO
  use hydro_parameters, ONLY: nvar
#endif
#ifdef TURB
  use turb_commons, ONLY: TURB_GS
#endif
  implicit none
  type(ramses_t) :: sim
  integer :: nborarrsize, ilevel

  allocate(grid(1:sim%m%ngridmax+sim%m%ncachemax))
  if(sim%r%nlevelmax > sim%r%levelmin)then
     allocate(flag1(1:twotondim,1:sim%m%ngridmax+sim%m%ncachemax))
     allocate(flag2(1:twotondim,1:sim%m%ngridmax+sim%m%ncachemax))
     allocate(father(1:sim%m%ngridmax+sim%m%ncachemax))
     flag1=0
     flag2=0
     father=0
  endif
  nborarrsize = (sim%m%ngridmax + nsubgridtondim - 1) / nsubgridtondim
  allocate(nbor(1:subgridsize,1:nborarrsize))
  nbor=0
  ! Allocate hash table space
  sim%m%hash_size=2*(sim%m%ngridmax+sim%m%ncachemax)
  allocate(hash_key(1:sim%m%hash_size))
  allocate(hash_val(1:sim%m%hash_size))
  hash_key=0
  hash_val=0
  ! Work buffers for GPU scan/sort/refine
  allocate(swap_local(1:sim%m%ngridmax+sim%m%ncachemax))
  allocate(swap_global(1:sim%m%ngridmax+sim%m%ncachemax))
  allocate(prefix_sum(1:sim%m%ngridmax+sim%m%ncachemax))
  allocate(partial_sums_0(1:max(1,(sim%m%ngridmax+sim%m%ncachemax)/256)))
  allocate(partial_sums_1(1:max(1,(sim%m%ngridmax+sim%m%ncachemax)/65536)))
  allocate(partial_sums_2(1:max(1,(sim%m%ngridmax+sim%m%ncachemax)/16777216)))
  swap_local=0
  swap_global=0
  prefix_sum=0

#ifdef HYDRO
  allocate(uold(1:twotondim,1:nvar,1:sim%m%ngridmax+sim%m%ncachemax))
  allocate(unew(1:twotondim,1:nvar,1:sim%m%ngridmax+sim%m%ncachemax))
  uold=0d0
  unew=0d0
#endif
#ifdef MHD
  allocate(bold(1:twotondim,1:6,1:sim%m%ngridmax+sim%m%ncachemax))
  allocate(bnew(1:twotondim,1:6,1:sim%m%ngridmax+sim%m%ncachemax))
  bold=0d0
  bnew=0d0
#endif
#ifdef TURB
  allocate(afield_last_d(1:ndim,0:TURB_GS-1,0:TURB_GS-1,0:TURB_GS-1))
  allocate(afield_next_d(1:ndim,0:TURB_GS-1,0:TURB_GS-1,0:TURB_GS-1))
  allocate(afield_now_d (1:ndim,0:TURB_GS-1,0:TURB_GS-1,0:TURB_GS-1))
  allocate(fturb(1:twotondim,1:3,1:sim%m%ngridmax+sim%m%ncachemax))
  afield_last_d=0d0
  afield_next_d=0d0
  afield_now_d=0d0
  fturb=0d0
#endif
#ifdef GRAV
  allocate(rho(1:twotondim,1:sim%m%ngridmax+sim%m%ncachemax))
  allocate(phi(1:twotondim,1:sim%m%ngridmax+sim%m%ncachemax))
  allocate(nref(1:twotondim,1:sim%m%ngridmax+sim%m%ncachemax))
  allocate(f(1:twotondim,1:3,1:sim%m%ngridmax+sim%m%ncachemax))
  allocate(phi_old(1:twotondim,1:sim%m%ngridmax+sim%m%ncachemax))
  f=0d0
  rho=0d0
  phi=0d0
  nref=0d0
  phi_old=0d0
#endif

  allocate(sim%m%head_cache(1:sim%r%nlevelmax))
  allocate(sim%m%tail_cache(1:sim%r%nlevelmax))
  allocate(sim%m%noct_cache(1:sim%r%nlevelmax))
  sim%m%head_cache=1
  sim%m%tail_cache=0
  sim%m%noct_cache=0
  sim%m%ifree_cache=1
  ! Compute Cartesian key offset for GPU hash table
  allocate(sim%m%key_off(1:sim%r%nlevelmax+1))
  sim%m%key_off(1)=1
  do ilevel=2,sim%r%nlevelmax+1
     sim%m%key_off(ilevel)=sim%m%key_off(ilevel-1)+sim%m%hkey_max(1,ilevel-1)
  end do
  ! Transfer debug parameter to host global
  gpu_debug = sim%r%debug
  ! Allocate and transfer bounding box to device
  allocate(ckey_max(1:sim%r%nlevelmax+1))
  allocate(key_off(1:sim%r%nlevelmax+1))
  allocate(box_ckey_min(1:3,1:sim%r%nlevelmax+1))
  allocate(box_ckey_max(1:3,1:sim%r%nlevelmax+1))
  ckey_max=sim%m%ckey_max
  key_off=sim%m%key_off
  periodic=sim%r%periodic
  box_size=sim%r%box_size
  constant_gravity=real(sim%r%constant_gravity,kind=dp)
  box_ckey_min=sim%m%box_ckey_min
  box_ckey_max=sim%m%box_ckey_max
  if(sim%r%nbound>0)then
     allocate(bound_ckey_min(1:3,1:sim%r%nbound,1:sim%r%nlevelmax+1))
     allocate(bound_ckey_max(1:3,1:sim%r%nbound,1:sim%r%nlevelmax+1))
     bound_ckey_min=sim%m%bound_ckey_min
     bound_ckey_max=sim%m%bound_ckey_max
  endif
  allocate(d_skip(1:ndim))
  d_skip = sim%m%skip

end subroutine gpu_allocate_amr
!###########################################################
!###########################################################
!###########################################################
!###########################################################
subroutine gpu_allocate_mg(sim)
  use amr_parameters, ONLY: ndim, twotondim, threetondim
  implicit none
  type(ramses_t) :: sim

#ifdef GRAV
  allocate(grid_mg(1:sim%m_mg%ngridmax+sim%m_mg%ncachemax))
  allocate(father_mg(1:sim%r%ngridmax+sim%r%ngridmax/7+sim%m_mg%ncachemax))
  allocate(nbor_mg(1:threetondim,1:sim%m_mg%ngridmax))
  father_mg=0
  nbor_mg=0
  ! Allocate hash table space
  sim%m_mg%hash_size=2*(sim%m_mg%ngridmax+sim%m_mg%ncachemax)
  allocate(hash_key_mg(1:sim%m_mg%hash_size))
  allocate(hash_val_mg(1:sim%m_mg%hash_size))
  hash_key_mg=0
  hash_val_mg=0
  allocate(phi_mg(1:twotondim,1:sim%m_mg%ngridmax+sim%m_mg%ncachemax))
  allocate(f_mg(1:twotondim,1:3,1:sim%m_mg%ngridmax+sim%m_mg%ncachemax))
#endif

end subroutine gpu_allocate_mg
!###########################################################
!###########################################################
!###########################################################
!###########################################################
subroutine gpu_allocate_part(sim)
  use amr_parameters, ONLY: ndim, twotondim
  use part_device, only: ensure_scan_capacity_part
  implicit none
  type(ramses_t) :: sim
  integer :: scan_size

  allocate(xp(1:sim%r%npartmax, 1:ndim))
  allocate(vp(1:sim%r%npartmax, 1:ndim))
  allocate(mp(1:sim%r%npartmax))
  allocate(levelp(1:sim%r%npartmax))
  allocate(sortp(1:sim%r%npartmax))
  if (sim%r%nlevelmax > sim%r%levelmin) allocate(idp(1:sim%r%npartmax))
#ifdef OUTPUT_PARTICLE_POTENTIAL
  allocate(phip(1:sim%r%npartmax))
#endif
  allocate(xp_swap(1:sim%r%npartmax))
  allocate(isp_swap(1:sim%r%npartmax))
  allocate(idp_swap(1:sim%r%npartmax))
  ! CUB workspace
#if defined(CUB_SORT_PART)
  allocate(hkeyp(1:sim%r%npartmax))
#endif
  ! Prefix sum arrays
  scan_size = max(sim%r%npartmax, (sim%m%ngridmax + sim%m%ncachemax) * twotondim)
  call ensure_scan_capacity_part(scan_size, sim%r%part_dep_algo)

end subroutine gpu_allocate_part
!###########################################################
!###########################################################
!###########################################################
!###########################################################
subroutine gpu_allocate_star(sim)
  use amr_parameters, ONLY: ndim, twotondim
  use part_device, only: ensure_scan_capacity_part
  implicit none
  type(ramses_t) :: sim
  integer :: scan_size

  allocate(star_xp(1:sim%r%nstarmax, 1:ndim))
  allocate(star_vp(1:sim%r%nstarmax, 1:ndim))
  allocate(star_mp(1:sim%r%nstarmax))
  allocate(star_tp(1:sim%r%nstarmax))
  allocate(star_zp(1:sim%r%nstarmax))
  allocate(star_sortp(1:sim%r%nstarmax))
  allocate(star_levelp(1:sim%r%nstarmax))
  if (sim%r%nlevelmax > sim%r%levelmin) allocate(star_idp(1:sim%r%nstarmax))
#ifdef OUTPUT_PARTICLE_POTENTIAL
  allocate(star_phip(1:sim%r%nstarmax))
#endif
  if (.not. allocated(xp_swap)) allocate(xp_swap(1:sim%r%nstarmax))
  if (.not. allocated(isp_swap)) allocate(isp_swap(1:sim%r%nstarmax))
  if (.not. allocated(idp_swap)) allocate(idp_swap(1:sim%r%nstarmax))
  ! CUB workspace
#if defined(CUB_SORT_PART)
  if (.not. allocated(hkeyp)) allocate(hkeyp(1:sim%r%nstarmax))
#endif
  ! Prefix sum arrays
  scan_size = max(sim%r%nstarmax, (sim%m%ngridmax + sim%m%ncachemax) * twotondim)
  call ensure_scan_capacity_part(scan_size, sim%r%star_dep_algo)

end subroutine gpu_allocate_star
!###########################################################
!###########################################################
!###########################################################
!###########################################################
subroutine gpu_allocate_sink(sim)
  use amr_parameters, ONLY: ndim, twotondim
  use part_device, only: ensure_scan_capacity_part
  implicit none
  type(ramses_t) :: sim
  integer :: scan_size

  allocate(sink_xp(1:sim%r%nsinkmax, 1:ndim))
  allocate(sink_vp(1:sim%r%nsinkmax, 1:ndim))
  allocate(sink_fp(1:sim%r%nsinkmax, 1:ndim))
  allocate(sink_jp(1:sim%r%nsinkmax, 1:ndim))
  allocate(sink_mp(1:sim%r%nsinkmax))
  allocate(sink_tp(1:sim%r%nsinkmax))
  allocate(sink_sortp(1:sim%r%nsinkmax))
  allocate(sink_levelp(1:sim%r%nsinkmax))
  allocate(sink_pid(1:sim%r%nsinkmax))
  if (sim%r%nlevelmax > sim%r%levelmin) allocate(sink_idp(1:sim%r%nsinkmax))
#ifdef OUTPUT_PARTICLE_POTENTIAL
  allocate(sink_phip(1:sim%r%nsinkmax))
#endif
  if (.not. allocated(xp_swap)) allocate(xp_swap(1:sim%r%nsinkmax))
  if (.not. allocated(isp_swap)) allocate(isp_swap(1:sim%r%nsinkmax))
  if (.not. allocated(idp_swap)) allocate(idp_swap(1:sim%r%nsinkmax))
  ! CUB workspace
#if defined(CUB_SORT_PART)
  if (.not. allocated(hkeyp)) allocate(hkeyp(1:sim%r%nsinkmax))
#endif
  ! Prefix sum arrays
  scan_size = max(sim%r%nsinkmax, (sim%m%ngridmax + sim%m%ncachemax) * twotondim)
  call ensure_scan_capacity_part(scan_size, sim%r%sink_dep_algo)

end subroutine gpu_allocate_sink
!###########################################################
!###########################################################
!###########################################################
!###########################################################
end module gpu_manager
