#pragma once
#ifdef MHD
#define NSUBGRID 2
#define MR_UCT_PRODUCT_FLUX_FIELDS 5
#define MR_UCT_PRODUCT_RECORD_FIELDS 5
#define MR_UCT_PRODUCT_FIELDS (MR_UCT_PRODUCT_FLUX_FIELDS + MR_UCT_PRODUCT_RECORD_FIELDS)
#define MR_UCT_PRODUCT_FACES (3 * (2 * NSUBGRID) * (2 * NSUBGRID) * (2 * NSUBGRID))
#define MR_SOLVER_LLF 1
#define MR_SOLVER_HLLD 4
#define MR_SOLVER_UCT_HLLD 7
#define MR_SOLVER2D_LLF 1
#define MR_SOLVER2D_HLLD 4
#else
#define NSUBGRID 1
#endif
